server:
  port: 8090
spring:
  application:
    name: mojiayi-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
      routes:
        - id: commission-path-route #路由的ID
          uri: lb://commission-service #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/commission-service/**
          filters:
            - StripPrefix=0
        - id: member-path-route
          uri: lb://member-service
          predicates:
            - Path=/api/member-service/**
          filters:
            - StripPrefix=0
    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748
logging:
  level:
    org.springframework:cloud.gateway: debug
route-id-name-map:
    # 这里的路由id必须与spring.cloud.gateway.routes.id里配置的相同
  commission-path-route: 佣金服务
  member-path-route: 会员服务
customize:
  consistent-hashing-urls:
    - /api/member-service/members/detail