server:
  port: 8088
  servlet:
    context-path: /api/member-service
spring:
  profiles:
    active: dev
  application:
    name: member-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8748
feign:
  sentinel:
    enabled: true