server:
  port: 8188
spring:
  application:
    name: mojiayi-gateway
  cloud:
    gateway:
      routes:
        - id: path_route #路由的ID
          uri: http://localhost:8089 #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/api/commission-service/**