server:
  port: 8089
  servlet:
    context-path: /api/commission-service
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: commission-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8748
feign:
  sentinel:
    enabled: true

customize:
  consistent-hashing-urls:
    - /api/member-service/members/detail