server:
  port: 8089
  servlet:
    context-path: /api/commission-service
spring:
  profiles:
    active: dev
  application:
    name: commission-service
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8748
feign:
  sentinel:
    enabled: true